### ISSUE TITLE
About page ?

### ISSUE THREAD

**Issue by jrfnl** [aron-bordin/neo-hpstr-jekyll-theme#5]
It looks like you removed the "_About_" page which was part of HPSTR, including the references to it in the theme setup, but in the homepage template, there is still a link to it which now 404's.

![screenshot](http://snag.gy/R5D7f.jpg)

P.S.: I really like what you've done with this theme!

**Comment by aron-bordin** [comment]
Hi,
Thx! 
Yes, I removed it and missed this point :P. It's better to add it again, thx

**Comment by jrfnl** [comment]
I've got a similar question about the featured images - looks like this was removed & then added back again, but not completely ?
Looks like it was only added back in the post template, not in the page or dark-post template. Also the documentation about it on the theme setup page has not been added back and the possibility to add credits for featured images either.

Was there any particular reason to do it this way ?

**Comment by aron-bordin** [comment]
Yes, I added it back this week, but only for post template, and the dark-post is new, so I'll need to add the featured image to it.

I don't have any plans of readding it to page template, it's different because in the original theme we have a large banner to show the image(http://mmistakes.github.io/hpstr-jekyll-theme/code-highlighting-post/), but in this fork, this same area is small, used only to display post information. What do you think about it ? Do you think that it's a good idea to have an option to show a featured image as a background for post title as well ?

Missing the credits, I'll add it.

I'm planning to rework in the setup page, I've made some modifications to this theme that need to be better documented, because my goal is to provide a theme that is easy to hack.

**Comment by jrfnl** [comment]
Let me think about it - I'm just now creating a site using your theme, so let's see what I run into.

Oh and I'll be sending in a number of pull requests in a little of things I've already found (including some inconsistencies in the theme setup page). Hope it helps ;-)

**Comment by aron-bordin** [comment]
Nice, thx

**Comment by jrfnl** [comment]
@aron-bordin Right, send in a load or PRs ;-) The first seven are ports of fixes which were added to HPSTR since you forked it off. The rest are new fixes I created, some of which I'm also submitting to HPSTR as well.

**Comment by aron-bordin** [comment]
@jrfnl Great work and thank you for these contributions, I'll be checking them this week.

**Comment by jrfnl** [comment]
Glad to help. As I was making these updates for my site anyway, I might as well share them ;-)

P.S.: at some point, you'll probably start getting merge conflicts. If you like, I'd be happy to rebase those PRs when you run into that.

**Comment by aron-bordin** [comment]
fixed in master, thx

**Comment by jrfnl** [comment]
Awesome! Thank you.
